server:
  port: 8080
spring:
  profiles:
    active: dev
  jpa:
    database: MYSQL
    show-sql: true
  mvc:
    static-path-pattern: classpath:/templates/**
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
  #    文件上传大小控制
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
mybatis:
  typeAliasesPackage: com.wuaipic.model
  mapperLocations: classpath:mapper/*.xml
logging:
  level:
    com.wuaipic.mapper: debug  #输出sql日志
---
server:
  port: 8081
  max-http-header-size: 4048576  #头文件接收的最大值
# 设置session过期时间
#  servlet:
#    session:
#      timeout: 1m
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wuaipic?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: password
    # REDIS (RedisProperties)
    # Redis数据库索引（默认为0）
  redis:
    database: 1
    host: 127.0.0.1
    port: 6379
#    password: 123456
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

file-path:
  image-path: d:/hello/

---

server:
  port: 8082
spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/wuaipic?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username: root
    password: password
    # REDIS (RedisProperties)
    # Redis数据库索引（默认为0）
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
      #    password: 123456
      jedis:
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 500
          min-idle: 0
      lettuce:
        shutdown-timeout: 0

  file-path:
    image-path: d:/hello/